#-=defining our values=-
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 960
SCREEN_TITLE = "crackrooms"
RIGHT_FACING = 0
LEFT_FACING = 1
CHARACTER_SCALING = 0.4
CURSOR_SCALING = 0.2
PLAYER_MOVEMENT_SPEED = 3
AMBIENT_COLOR = (0, 0, 0)
TILE_SCALING = 0.4
SPRINT_SPEED = 2
SPRITE_SPEED = 3.1